Draw card
CSC207-2022F-UofT/course-project-smmmack pull request #28
Opened 2022-11-22 01:06 UTC by mariamustard21

Unfinished pull request for DrawCard!

2022-11-22 02:06 UTC, no7thing commented
Good progress so far, make sure you implement and fix the input data file, as it is important! otherwise good job!

2022-11-22 03:07 UTC, Maxlyu254 requested changes
You shouldn't merge this to the main branch yet, the program failed to pass the java classroom check. Try to find out what's wrong.

2022-11-25 20:46 UTC, Maxlyu254 approved these changes
Although there are some problems, it can compile, so pull request approved

2022-11-25 20:58 UTC, celinayueh submitted a review, later dismissed
Good job finishing the use case and following clean architecture. Some changes will need to be made to follow MVVM model.

2022-11-25 21:28 UTC, sinemsoylemezoglu submitted a review, later dismissed
Good job on the Draw Card use case Maria. Need to change the Presenter class.

2022-12-01 19:34 UTC, Maxlyu254 requested changes
Your classroom checks failed, please try to fix that problem

2022-12-02 12:52 UTC, zhenzeyang commented
You made a lot progress! Good job! For now you need to make your code pass the checker and update the view model

2022-12-02 20:55 UTC, adelinewang3 reviewed
My use case doesn't use input data as well, you can take a look at it to see how you might implement yours

2022-12-02 20:55 UTC, adelinewang3 commented on src/main/java/DrawCard/DrawCardInteractor.java
> +    final Player player;
you should access the player information from the CampaignAccess

2022-12-02 20:55 UTC, adelinewang3 commented on src/main/java/DrawCard/DrawCardInputData.java
> +    public DrawCardInputData(String playerName, Deck deckType) {
Your use case does not need any input data. Once a player lands on a tile, the advance use case will determine what tile it is and call the appropriate use case (in jail, draw card, pay rent, etc.).

2022-12-07 19:17 UTC, closed without merging